const blogs = [
    {
      id: "1",
      title: "How Laravel 11 Improves API Development Speed and Security",
      screens: "/images/blog/img-1.jpg",
      description:
        "A deep dive into Laravel 11’s new API features, authentication improvements, and performance optimizations that help developers ship faster and safer applications.",
      author: "Rehan Akram",
      authorTitle: "Full-Stack Developer",
      create_at: "25 Jan, 2025",
      blogSingleImg: "/images/blog-details/img-1.jpg",
      comment: "12",
      blClass: "format-standard-image",
    },
    {
      id: "2",
      title: "Best Practices for Building Scalable ASP.NET Core Applications",
      screens: "/images/blog/img-2.jpg",
      description:
        "Learn how to architect your ASP.NET Core applications for scalability, including database optimization, dependency injection, and API performance tuning.",
      author: "Rehan Akram",
      authorTitle: "Software Engineer",
      create_at: "12 Jan, 2025",
      blogSingleImg: "/images/blog-details/img-2.jpg",
      comment: "18",
      blClass: "format-standard-image",
    },
    {
      id: "3",
      title: "ReactJS State Management with Pinia, Redux, and Context API",
      screens: "/images/blog/img-3.jpg",
      description:
        "Comparing modern state management solutions for ReactJS projects, and how to choose the right one for performance, scalability, and developer experience.",
      author: "Rehan Akram",
      authorTitle: "Frontend Specialist",
      create_at: "05 Jan, 2025",
      blogSingleImg: "/images/blog-details/img-3.jpg",
      comment: "25",
      blClass: "format-video",
    },
    {
      id: "4",
      title: "Integrating Payment Gateways in Laravel and ASP.NET Core",
      screens: "/images/blog/img-4.jpg",
      description:
        "Step-by-step guide to integrating Stripe, PayPal, and SSLCommerz in Laravel and ASP.NET Core projects while ensuring security and compliance.",
      author: "Rehan Akram",
      authorTitle: "Full-Stack Developer",
      create_at: "20 Dec, 2024",
      blogSingleImg: "/images/blog-details/img-4.jpg",
      comment: "30",
      blClass: "format-standard-image",
    },
    {
      id: "5",
      title: "Optimizing MySQL and MSSQL Databases for High-Traffic Websites",
      screens: "/images/blog/img-5.jpg",
      description:
        "Tips and techniques for indexing, query optimization, and caching to handle millions of requests efficiently in Laravel and ASP.NET applications.",
      author: "Rehan Akram",
      authorTitle: "Database Specialist",
      create_at: "15 Dec, 2024",
      blogSingleImg: "/images/blog-details/img-5.jpg",
      comment: "16",
      blClass: "format-standard-image",
    },
    {
      id: "6",
      title: "Building a Real-Time Chat App with Laravel WebSockets and ReactJS",
      screens: "/images/blog/img-6.jpg",
      description:
        "A step-by-step tutorial on creating a real-time chat application using Laravel WebSockets and a ReactJS frontend for seamless communication.",
      author: "Rehan Akram",
      authorTitle: "Full-Stack Engineer",
      create_at: "08 Dec, 2024",
      blogSingleImg: "/images/blog-details/img-6.jpg",
      comment: "22",
      blClass: "format-standard-image",
    },
    {
      id: "7",
      title: "Implementing Two-Factor Authentication in Laravel and ASP.NET",
      screens: "/images/blog/img-7.jpg",
      description:
        "Learn how to enhance application security by adding 2FA with email, SMS, and authenticator apps in both Laravel and ASP.NET Core projects.",
      author: "Rehan Akram",
      authorTitle: "Security Specialist",
      create_at: "01 Dec, 2024",
      blogSingleImg: "/images/blog-details/img-7.jpg",
      comment: "19",
      blClass: "format-standard-image",
    },
    {
      id: "8",
      title: "Deploying Laravel, ASP.NET, and React Projects to Production",
      screens: "/images/blog/img-8.jpg",
      description:
        "Best practices for deploying full-stack applications to cloud servers, including CI/CD pipelines, Docker, and environment configuration.",
      author: "Rehan Akram",
      authorTitle: "DevOps Enthusiast",
      create_at: "25 Nov, 2024",
      blogSingleImg: "/images/blog-details/img-8.jpg",
      comment: "27",
      blClass: "format-standard-image",
    },
    {
      id: "9",
      title: "Building an E-commerce Platform with Laravel and ReactJS",
      screens: "/images/blog/img-9.jpg",
      description:
        "How to create a fully functional e-commerce site with Laravel as the backend and ReactJS as the frontend, including payment and cart features.",
      author: "Rehan Akram",
      authorTitle: "E-commerce Developer",
      create_at: "18 Nov, 2024",
      blogSingleImg: "/images/blog-details/img-9.jpg",
      comment: "15",
      blClass: "format-standard-image",
    },
    {
      id: "10",
      title: "Mastering RESTful API Development in ASP.NET Core",
      screens: "/images/blog/img-10.jpg",
      description:
        "A complete guide to designing and building RESTful APIs in ASP.NET Core with authentication, validation, and performance optimization.",
      author: "Rehan Akram",
      authorTitle: "Backend Developer",
      create_at: "10 Nov, 2024",
      blogSingleImg: "/images/blog-details/img-10.jpg",
      comment: "21",
      blClass: "format-standard-image",
    },
    {
      id: "11",
      title: "Creating SEO-Friendly Websites with Next.js and Laravel APIs",
      screens: "/images/blog/img-11.jpg",
      description:
        "Boost your website’s SEO by leveraging Next.js for server-side rendering while fetching data from Laravel-powered APIs.",
      author: "Rehan Akram",
      authorTitle: "Full-Stack Developer",
      create_at: "02 Nov, 2024",
      blogSingleImg: "/images/blog-details/img-11.jpg",
      comment: "14",
      blClass: "format-standard-image",
    },
    {
      id: "12",
      title: "Building Multi-Tenant Applications in Laravel and ASP.NET",
      screens: "/images/blog/img-12.jpg",
      description:
        "Architecting multi-tenant SaaS platforms with role-based access and isolated databases in both Laravel and ASP.NET Core.",
      author: "Rehan Akram",
      authorTitle: "SaaS Developer",
      create_at: "28 Oct, 2024",
      blogSingleImg: "/images/blog-details/img-12.jpg",
      comment: "18",
      blClass: "format-standard-image",
    },
  ];
  
  export default blogs;
  