const Projects = [
  {
    Id: "1",
    pImg: "images/project/accounting-inventory-thumb.png",
    ps1img: "images/project-single/accounting-inventory-main.png",
    psub1img1: "images/project-single/accounting-inventory-page1.jpg",
    psub1img2: "images/project-single/accounting-inventory-page2.jpg",
    title: "ERP-(Accounting, Inventory & POS)",
    subTitle:
      "Laravel / jQuery / MySql / ERP / Accounting / Stock Control / Inventory / POS",
    slug: "erp-accounting-inventory-pos-laravel",
  },
  {
    Id: "2",
    pImg: "images/project/evat-thumb.jpg",
    ps1img: "images/project-single/evat-main.jpg",
    psub1img1: "images/project-single/evat-page1.jpg",
    psub1img2: "images/project-single/evat-page2.jpg",
    title: "EVAT Application – NBR Approved",
    subTitle: "ASP.NET Core / jQuery / SqlServer /  VAT Management",
    slug: "evat-application-aspnet",
  },
  {
    Id: "3",
    pImg: "images/project/hrms-thumb.jpg",
    ps1img: "images/project-single/hrms-main.jpg",
    psub1img1: "images/project-single/hrms-page1.jpg",
    psub1img2: "images/project-single/hrms-page2.jpg",
    title: "HR Management System",
    subTitle: "Laravel / HR & Payroll",
    slug: "hrms-laravel",
  },
  {
    Id: "4",
    pImg: "images/project/pos-thumb.jpg",
    ps1img: "images/project-single/pos-main.jpg",
    psub1img1: "images/project-single/pos-page1.jpg",
    psub1img2: "images/project-single/pos-page2.jpg",
    title: "POS & Inventory Management System",
    subTitle: "ASP.NET Core / POS / Inventory",
    slug: "pos-aspnet",
  },
  {
    Id: "5",
    pImg: "images/project/warranty-system-thumb.jpg",
    ps1img: "images/project-single/warranty-system-main.jpg",
    psub1img1: "images/project-single/warranty-system-page1.jpg",
    psub1img2: "images/project-single/warranty-system-page2.jpg",
    title: "Warranty Management System",
    subTitle: "ASP.NET Core / Warranty Tracking",
    slug: "warranty-management-aspnet",
  },
  {
    Id: "10",
    pImg: "images/project/whatsapp-clone-thumb.jpg",
    ps1img: "images/project-single/whatsapp-clone-main.jpg",
    psub1img1: "images/project-single/whatsapp-clone-page1.jpg",
    psub1img2: "images/project-single/whatsapp-clone-page2.jpg",
    title: "WhatsApp Clone – Real-Time Chat App",
    subTitle: "ReactJS / Laravel / WebSocket",
    slug: "whatsapp-clone-react-laravel",
  },
  {
    Id: "11",
    pImg: "images/project/currency-exchange-thumb.jpg",
    ps1img: "images/project-single/currency-exchange-main.jpg",
    psub1img1: "images/project-single/currency-exchange-page1.jpg",
    psub1img2: "images/project-single/currency-exchange-page2.jpg",
    title: "Currency Exchange Application",
    subTitle: "Laravel / Exchange Rates API",
    url: "https://adminswap.com/",
    adminUrl: "https://adminswap.com/admin",
    slug: "currency-exchange-laravel",
  },
  {
    Id: "12",
    pImg: "images/project/map-ncare-thumb.jpg",
    ps1img: "images/project-single/map-ncare-main.jpg",
    psub1img1: "images/project-single/map-ncare-page1.jpg",
    psub1img2: "images/project-single/map-ncare-page2.jpg",
    title: "Map nCare Project",
    subTitle: "Vue.js / Laravel API / Map Integration",
    slug: "map-ncare-vue-laravel",
  },
  {
    Id: "13",
    pImg: "images/project/inventory-thumb.jpg",
    ps1img: "images/project-single/inventory-main.jpg",
    psub1img1: "images/project-single/inventory-page1.jpg",
    psub1img2: "images/project-single/inventory-page2.jpg",
    title: "Inventory Management",
    subTitle: "ASP.NET Core / MSSQL",
    slug: "inventory-laravel",
  },
  {
    Id: "14",
    pImg: "images/project/brothersaccountants-frontend-thumb.jpg",
    ps1img: "images/project-single/brothersaccountants-frontend-main.jpg",
    psub1img1: "images/project-single/brothersaccountants-frontend-page1.jpg",
    psub1img2: "images/project-single/brothersaccountants-frontend-page2.jpg",
    title: "Brothers Accountants – Frontend",
    subTitle: "ReactJS / Next.js",
    slug: "brothersaccountants-frontend-react",
  },
  {
    Id: "15",
    pImg: "images/project/brothersaccountants-backend-thumb.jpg",
    ps1img: "images/project-single/brothersaccountants-backend-main.jpg",
    psub1img1: "images/project-single/brothersaccountants-backend-page1.jpg",
    psub1img2: "images/project-single/brothersaccountants-backend-page2.jpg",
    title: "Brothers Accountants – Backend",
    subTitle: "Laravel / API Development",
    slug: "brothersaccountants-backend-laravel",
  },
  {
    Id: "16",
    pImg: "images/project/ecommerce-thumb.jpg",
    ps1img: "images/project-single/ecommerce-main.jpg",
    psub1img1: "images/project-single/ecommerce-page1.jpg",
    psub1img2: "images/project-single/ecommerce-page2.jpg",
    title: "E-commerce Project with Uber Eats Features",
    subTitle: "Laravel / Food Delivery",
    slug: "laravel-ecommerce-ubereats",
  },
  {
    Id: "17",
    pImg: "images/project/chrome-auto-reload-thumb.jpg",
    ps1img: "images/project-single/chrome-auto-reload-main.jpg",
    psub1img1: "images/project-single/chrome-auto-reload-page1.jpg",
    psub1img2: "images/project-single/chrome-auto-reload-page2.jpg",
    title: "Chrome Extension – Auto Reload Background Tab",
    subTitle: "JavaScript / Chrome Extension",
    slug: "chrome-extension-auto-reload",
  },
  //   {
  //     Id: "7",
  //     pImg: "images/project/portfolio-react-thumb.jpg",
  //     ps1img: "images/project-single/portfolio-react-main.jpg",
  //     psub1img1: "images/project-single/portfolio-react-page1.jpg",
  //     psub1img2: "images/project-single/portfolio-react-page2.jpg",
  //     title: "Personal Portfolio – React & Next.js",
  //     subTitle: "ReactJS / Next.js / Portfolio",
  //     slug: "portfolio-react-nextjs",
  //   },
  //   {
  //     Id: "8",
  //     pImg: "images/project/qrcode-generator-thumb.jpg",
  //     ps1img: "images/project-single/qrcode-generator-main.jpg",
  //     psub1img1: "images/project-single/qrcode-generator-page1.jpg",
  //     psub1img2: "images/project-single/qrcode-generator-page2.jpg",
  //     title: "QR Code Generator Web App",
  //     subTitle: "Laravel / QR Code",
  //     slug: "qr-code-generator-laravel",
  //   },
  //   {
  //     Id: "9",
  //     pImg: "images/project/todo-spa-thumb.jpg",
  //     ps1img: "images/project-single/todo-spa-main.jpg",
  //     psub1img1: "images/project-single/todo-spa-page1.jpg",
  //     psub1img2: "images/project-single/todo-spa-page2.jpg",
  //     title: "SPA To-Do Application",
  //     subTitle: "ReactJS / Laravel API",
  //     slug: "todo-spa-react-laravel",
  //   },
  // {
  //    Id: '1',
  //    pImg: 'images/project/healthcalcpro-thumb.jpg',
  //    ps1img: 'images/project-single/healthcalcpro-main.jpg',
  //    psub1img1: 'images/project-single/healthcalcpro-page1.jpg',
  //    psub1img2: 'images/project-single/healthcalcpro-page2.jpg',
  //    title: 'HealthCalcPro – Laravel Health & Fitness Calculator',
  //    subTitle: 'Laravel / Health App',
  //    slug: 'healthcalcpro-laravel'
  // },
];

export default Projects;
